/*
 * Maze Game API
 * A simple single-player maze game.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.client.model.GameStatusDto;
import org.openapitools.client.model.PositionDto;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GameDto
 */
class GameDtoTest {
    private final GameDto model = new GameDto();

    /**
     * Model tests for GameDto
     */
    @Test
    void testGameDto() {
        // TODO: test GameDto
    }

    /**
     * Test the property 'gameId'
     */
    @Test
    void gameIdTest() {
        // TODO: test gameId
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'position'
     */
    @Test
    void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

}
