/*
 * Maze Game API
 * A simple single-player maze game.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.openapitools.client.model.DirectionDto;
import org.openapitools.client.model.MoveStatusDto;
import org.openapitools.client.model.PositionDto;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MoveDto
 */
class MoveDtoTest {
    private final MoveDto model = new MoveDto();

    /**
     * Model tests for MoveDto
     */
    @Test
    void testMoveDto() {
        // TODO: test MoveDto
    }

    /**
     * Test the property 'moveId'
     */
    @Test
    void moveIdTest() {
        // TODO: test moveId
    }

    /**
     * Test the property 'direction'
     */
    @Test
    void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'positionAfterMove'
     */
    @Test
    void positionAfterMoveTest() {
        // TODO: test positionAfterMove
    }

    /**
     * Test the property 'moveStatus'
     */
    @Test
    void moveStatusTest() {
        // TODO: test moveStatus
    }

}
