/*
 * Maze Game API
 * A simple single-player maze game.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MoveStatusDto
 */
class MoveStatusDtoTest {
    /**
     * Model tests for MoveStatusDto
     */
    @Test
    void testMoveStatusDto() {
        // TODO: test MoveStatusDto
    }

}
