/*
 * Maze Game API
 * A simple single-player maze game.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PositionDto
 */
class PositionDtoTest {
    private final PositionDto model = new PositionDto();

    /**
     * Model tests for PositionDto
     */
    @Test
    void testPositionDto() {
        // TODO: test PositionDto
    }

    /**
     * Test the property 'positionX'
     */
    @Test
    void positionXTest() {
        // TODO: test positionX
    }

    /**
     * Test the property 'positionY'
     */
    @Test
    void positionYTest() {
        // TODO: test positionY
    }

}
